### ISSUE TITLE
go get github.com/ClarkGuan/scrcpy-go 错误

### ISSUE THREAD

**Issue by tommyxps** [ClarkGuan/scrcpy-go#1]
运行后出现 

pkg-config --cflags  -- sdl2
pkg-config: exec: "pkg-config": executable file not found in $PATH

**Comment by ClarkGuan** [comment]
错误提示显示：命令 pkg-config 在 $PATH 环境变量中找不到。
也就是说，你没有安装 pkg-config 这个命令。
