### ISSUE TITLE
Error while fetching and compiling

### ISSUE THREAD

**Issue by Genxster1998** [ClarkGuan/scrcpy-go#2]
$ go get github.com/ClarkGuan/scrcpy-go
# github.com/ClarkGuan/go-sdl2/sdl
../go/src/github.com/ClarkGuan/go-sdl2/sdl/hints.go:107:50: could not determine kind of name for C.SDL_HINT_ANDROID_SEPARATE_MOUSE_AND_TOUCH

**Comment by ClarkGuan** [comment]
@Genxster1998 已更新 go-sdl 的代码，可以重新 go get -u github.com/ClarkGuan/scrcpy-go 试一下
